s="ACCGTCTCATCGGGTTGTATACAGACGCTAGAGTCGCGACACATGTATTTCTCGCAGGCATCTTGGAGATGGCGGCGAAGCTGTTCATCACCAGCGGTTAGCAAGTGTAGACCACTACCCATCCGGGGTCGCCACTGCACACATTCATATTTACATTAGATTCGACAGCTAAGACGACAGACGAGTAAACTACAATCTTCAGGGAATCAGGGCCTGGTCCTAGAGGAAATGCGTAACCTGAGTTTAGTCTATCTGCTGCGTTAATGGTTACACAAAGGCCCCACGACCGGCTTGGGAGAGTCATACGGGATATACTACACACATCCTCTGCTTAAACGGCTGAGTGTCATGGAGAGGCCTCCCAACATTATATCCTTACCAATGGGTGTGCGGAGTTTATGGCTACCCGGCTATCGAGGTACAAGGATGGTCAGACCAGTCGGAATACATTGGTATATGACACCCAGGTTCTATAGTTTATCAAAGTACACACACTAACCTGTGCAAGCAACATATCTGACGCTCTCAAAACAGTCGTCTTCTGTGTCGGGCTTTAATTCCCGATCGAAGACCTAACACTCTCGCCTGCGCCCACCGAATCGAGATTATCAAAGCAGTAGAGAAACCTAGTGCTTCAGCAGCTGCGCGTAGTGACGTGTCCATTAGTAGCAATACGAAGATGGGTGATTATAGTTGAGAGTTCGATGATCGGGCATGCCCAACCTTGTCAGAATTGTCCGGTATGCAGTCTAGTATTCGGACTTCGTGCCAAGCATGGGCAGTGAGAAGCCCACATTGCCCTAAGGTACGTCACGTAGATGTTATGATATTTTCTATAAGGCACTTGTACTCTCTTGCAGGACCGGAACAGAGGGAAA"
t="GTGCGCAACCCCTGGTGCGCG"
def spliced(s, t):
    index = []
    a = 0
    while a < len(s):
        while len(t) > 0:
            if s[a] == t[0]:
                index.append(a+1)
                t = t[1:]
            a += 1
        return(index)

print(spliced(s,t))
