s = "CTGGAGCAATGCGGACTACTCCGCTCTGGAGCGACTGGAGCGCTGGAGCTGTTCCTGGAGCCTGGAGCGCTGGAGCCTGGAGCTCATCTGGAGCCTGGAGCTTGAGCTGGAGCCCTGGAGCTACACCAGCCCTGGAGCTTTTTGGCCTGGAGCGCCTGGAGCCTGGAGCCTGGAGCCTGGAGCGAATGATATAAGCTGGAGCCCTTTGCTGGAGCCTCCTGGAGCCTGGAGCGGTACTCCGCTGGAGCGTCTGGAGCGAGGTCACTGGAGCCTGGAGCCTGGAGCTCCCCTGGAGCCTGGAGCACTGGAGCCTGGAGCCGAGCTTACATTACTGGAGCTCGCCCCTGGAGCCTGGAGCCCTGGAGCCTGTACCTGTGACTGGAGCCTCTGGAGCTCTGGAGCACTGGAGCCGCTGGAGCGCACACCTGGAGCGGGCATAACTGGAGCTCGACTGGAGCCTGGAGCCAGTGTTTCTGGAGCCCTGGAGCCTGGAGCATGCGTGCCCCTGGAGCAGGAACGTACTGGAGCACCTGGAGCACTGGAGCTTTTGTTCTGGAGCGGCTGGAGCTGCAAATATAACGCTGGAGCTCTGGAGCTCCTGGAGCTACTGGAGCCTGGAGCCTGGAGCATACTGGAGCCTGGAGCCTGGAGCTCCTGGAGCACTGGAGCGACTAACTGGAGCCTGGAGCGTGTGTACTGGAGCACTGGAGCTATTGCTGGAGCGAACTGGAGCCCTGGAGCAGCTGGAGCCTGGAGCCGCTGGAGCTACTGGAGCATGCAGCTGGAGCCTGGAGC"
t = "CTGGAGCCT"
location = []

for i in range(0, len(s) - len(t) + 1):
    if s[i:i+len(t)] == t:
        location.append(i+1)

for i in location:
    print (i, end = ' ')
